### ISSUE TITLE
Add support for specifying selected resources to record

### ISSUE THREAD

**Issue by Dysproz** [cloudposse/terraform-aws-config#38]
## Describe the Feature

Add support for specifying selected resources to record as it is possible to set in configuration from AWS console:
![image](https://user-images.githubusercontent.com/17621853/137292236-262746a6-2c98-40e7-8d2a-68bf37143ad6.png)

Probably adding [this](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/config_configuration_recorder#resource_types) field to input variables would do the job.

## Expected Behavior

Variable that allows to set resource types to record.

## Use Case

My use case rewrites [this](https://aws.amazon.com/blogs/security/how-to-use-aws-config-to-monitor-for-and-respond-to-amazon-s3-buckets-allowing-public-access) blogpost into terraform and tries to configure AWS Config using your module.

## Describe Ideal Solution

Adding variable that allows to set resource types to record.

## Alternatives Considered

-

## Additional Context

-

**Comment by Nuru** [comment]
Closed vi #87

**Comment by colonnac** [comment]
No this is not closed:
you need a variable to fill this value
https://github.com/cloudposse/terraform-aws-config/blob/main/main.tf#L16-L17
